version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_society_db
    ports:
      - "3306:3306"
    networks:
      - backend

  e-society-app:
    build: .
    container_name: e-society-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
